//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitCode
{
    using GitCode.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GitCodeEDMContainer : DbContext
    {
        public GitCodeEDMContainer()
            : base("name=GitCodeEDMContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<DetailTeam> DetailTeams { get; set; }
        public DbSet<Class> Classes { get; set; }
        public DbSet<DetailClass> DetailClasses { get; set; }
        public DbSet<DetailClassAccess> DetailClassAccesses { get; set; }
        public DbSet<DetailRepository> DetailRepositories { get; set; }
        public DbSet<Repository> Repositories { get; set; }
        public DbSet<Feature> Features { get; set; }
        public DbSet<Issue> Issues { get; set; }
        public DbSet<Wiki> Wikis { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<WikiDetail> WikiDetails { get; set; }
        public DbSet<GitCodeBase> GitCodeBases { get; set; }
    }
}
