// <auto-generated />
namespace GitCode.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class newEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201404151105171_newEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
